version: "4.0"

services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME_PREFIX}_express_app
    env_file: 
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - MONGO_URI=${MONGO_URI}
      - IQAIR_API_KEY=${IQAIR_API_KEY}
      - IQAIR_BASE_URL=${IQAIR_BASE_URL}
    depends_on:
      - mongo
    command: npm run ${NODE_ENV}

  mongo:
    image: mongo:6.0
    container_name: ${CONTAINER_NAME_PREFIX}_mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
